# Site settings
title: "#campuslauf16"
email: marie.timcke@journocode.com
url: http://www.tu-campuslauf.de
description: "Am 11. Mai fällt der Startschuss zum 32. Campuslauf der TU Dortmund.
Wieder werden sich Studierende und Externe in verschiedenen Disziplinen wie
dem Mathetower-Run oder dem Campuswalk messen.
In einem Countdown stimmt euch das Ressort <strong>Campus und Leben</strong> der
Pflichtlektüre Online
darauf ein und berichtet live vom Campussportevent des Jahres!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "Pflichtlektüre Online"


# Team names, titles and social links
people:
- name: Marie-Louise Timcke
  pic: 1
  position: Webentwicklung & Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
    - title: github
      url: https://github.com/marielouiese
    - title: globe
      url: http://datentaeter.de/

- name: Sakander Zirai
  pic: 2
  position: Webentwicklung
  social:
    - title: twitter
      url: http://www.twitter.com/suioni
    - title: github
      url: https://github.com/suioni
  #  - title: globe
  #    url: #


people2:
- name: Johannes Mohren
  pic: 7
  position: Ressortleitung
  social:
    - title: twitter
      url: https://twitter.com/Johannes_Mohren
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Julia Bernewasser
  pic: 8
  position: Ressortleitung
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Wenke Wensing
  pic: 3
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/Wenke_we
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Carola Kortfunke
  pic: 4
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #


- name: Hanna Heine
  pic: 5
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Lena Meerkötter
  pic: 6
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/Lena_m_m95
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Megan
  pic: 1
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Mara Desranges
  pic: 2
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: globe
    url: http://pflichtlektuere.com
  - title: twitter
    url: http://twitter.com/pflichtlektuere
  - title: facebook
    url: https://www.facebook.com/Pflichtlektuere-148575178511113/?fref=ts
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll




# Build settings
markdown: kramdown
permalink: pretty


# carousel Bilder
carousel:
  - image: slider/theme/slide1.png
  - image: slider/theme/slide2.png
  - image: slider/theme/slide3.png
  - image: slider/theme/slide4.png
#  - image: slider/theme/slide5.png
#  - image: slider/theme/slide6.png
#  - image: slider/theme/slide7.png
#  - image: slider/theme/slide8.png
#  - image: slider/theme/slide9.png
#  - image: slider/theme/slide10.png
#  - image: slider/theme/slide11.png
#  - image: slider/theme/slide12.png
#  - image: slider/theme/slide13.png
#  - image: slider/theme/slide14.png
#  - image: slider/theme/slide15.png
#  - image: slider/theme/slide16.png
#  - image: slider/theme/slide17.png
#  - image: slider/theme/slide18.png
#  - image: slider/theme/slide19.png
#  - image: slider/theme/slide20.png
#  - image: slider/theme/slide21.png
#  - image: slider/theme/slide22.png
#  - image: slider/theme/slide23.png
#  - image: slider/theme/slide24.png
#  - image: slider/theme/slide25.png
#  - image: slider/theme/slide26.png
#  - image: slider/theme/slide27.png
#  - image: slider/theme/slide28.png
#  - image: slider/theme/slide29.png
#  - image: slider/theme/slide30.png
#  - image: slider/theme/slide31.png
#  - image: slider/theme/slide32.png
#  - image: slider/theme/slide33.png
#  - image: slider/theme/slide34.png
#  - image: slider/theme/slide35.png
#  - image: slider/theme/slide36.png
#  - image: slider/theme/slide37.png
#  - image: slider/theme/slide38.png
#  - image: slider/theme/slide39.png
#  - image: slider/theme/slide40.png
#  - image: slider/theme/slide41.png
#  - image: slider/theme/slide42.png
#  - image: slider/theme/slide43.png
#  - image: slider/theme/slide44.png
#  - image: slider/theme/slide45.png
#  - image: slider/theme/slide46.png
#  - image: slider/theme/slide47.png
#  - image: slider/theme/slide48.png
#  - image: slider/theme/slide49.png
#  - image: slider/theme/slide50.png
#  - image: slider/theme/slide51.png
#  - image: slider/theme/slide52.png
#  - image: slider/theme/slide53.png
#  - image: slider/theme/slide54.png
#  - image: slider/theme/slide55.png
#  - image: slider/theme/slide56.png
#  - image: slider/theme/slide57.png
#  - image: slider/theme/slide58.png
#  - image: slider/theme/slide59.png
#  - image: slider/theme/slide60.png
#  - image: slider/theme/slide61.png
#  - image: slider/theme/slide62.png
#  - image: slider/theme/slide63.png
#  - image: slider/theme/slide64.png
#  - image: slider/theme/slide65.png
#  - image: slider/theme/slide66.png
#  - image: slider/theme/slide67.png
#  - image: slider/theme/slide68.png
#  - image: slider/theme/slide69.png
#  - image: slider/theme/slide70.png
#  - image: slider/theme/slide71.png
#  - image: slider/theme/slide72.png
#  - image: slider/theme/slide73.png
#  - image: slider/theme/slide74.png
#  - image: slider/theme/slide75.png
#  - image: slider/theme/slide76.png
#  - image: slider/theme/slide77.png
#  - image: slider/theme/slide78.png
#  - image: slider/theme/slide79.png
#  - image: slider/theme/slide80.png
#  - image: slider/theme/slide81.png
#  - image: slider/theme/slide82.png
#  - image: slider/theme/slide83.png
#  - image: slider/theme/slide84.png
#  - image: slider/theme/slide85.png
#  - image: slider/theme/slide86.png
#  - image: slider/theme/slide87.png
#  - image: slider/theme/slide88.png
#  - image: slider/theme/slide89.png
#  - image: slider/theme/slide90.png
#  - image: slider/theme/slide91.png
#  - image: slider/theme/slide92.png
#  - image: slider/theme/slide93.png
#  - image: slider/theme/slide94.png
#  - image: slider/theme/slide95.png
#  - image: slider/theme/slide96.png
#  - image: slider/theme/slide97.png
#  - image: slider/theme/slide98.png
#  - image: slider/theme/slide99.png
#  - image: slider/theme/slide100.png
#  - image: slider/theme/slide101.png
#  - image: slider/theme/slide102.png
#  - image: slider/theme/slide103.png
#  - image: slider/theme/slide104.png
#  - image: slider/theme/slide105.png
#  - image: slider/theme/slide106.png
#  - image: slider/theme/slide107.png
#  - image: slider/theme/slide108.png
#  - image: slider/theme/slide109.png
#  - image: slider/theme/slide110.png
#  - image: slider/theme/slide111.png
#  - image: slider/theme/slide112.png
#  - image: slider/theme/slide113.png
#  - image: slider/theme/slide114.png
#  - image: slider/theme/slide115.png
#  - image: slider/theme/slide116.png
#  - image: slider/theme/slide117.png
#  - image: slider/theme/slide118.png
#  - image: slider/theme/slide119.png
#  - image: slider/theme/slide120.png
#  - image: slider/theme/slide121.png
#  - image: slider/theme/slide122.png
#  - image: slider/theme/slide123.png
#  - image: slider/theme/slide124.png
#  - image: slider/theme/slide125.png
#  - image: slider/theme/slide126.png
#  - image: slider/theme/slide127.png
#  - image: slider/theme/slide128.png
#  - image: slider/theme/slide129.png
#  - image: slider/theme/slide130.png
#  - image: slider/theme/slide131.png
#  - image: slider/theme/slide132.png
#  - image: slider/theme/slide133.png
#  - image: slider/theme/slide134.png
#  - image: slider/theme/slide135.png
#  - image: slider/theme/slide136.png
#  - image: slider/theme/slide137.png
#  - image: slider/theme/slide138.png
#  - image: slider/theme/slide139.png
#  - image: slider/theme/slide140.png
#  - image: slider/theme/slide141.png
#  - image: slider/theme/slide142.png
#  - image: slider/theme/slide143.png
#  - image: slider/theme/slide144.png
#  - image: slider/theme/slide145.png
#  - image: slider/theme/slide146.png
#  - image: slider/theme/slide147.png
#  - image: slider/theme/slide148.png
#  - image: slider/theme/slide149.png
#  - image: slider/theme/slide150.png
#  - image: slider/theme/slide151.png
#  - image: slider/theme/slide152.png
#  - image: slider/theme/slide153.png
#  - image: slider/theme/slide154.png
#  - image: slider/theme/slide155.png
#  - image: slider/theme/slide156.png
#  - image: slider/theme/slide157.png
#  - image: slider/theme/slide158.png
#  - image: slider/theme/slide159.png
#  - image: slider/theme/slide160.png
#  - image: slider/theme/slide161.png
#  - image: slider/theme/slide162.png
#  - image: slider/theme/slide163.png
#  - image: slider/theme/slide164.png
#  - image: slider/theme/slide165.png
#  - image: slider/theme/slide170.png
#  - image: slider/theme/slide171.png
#  - image: slider/theme/slide172.png
#  - image: slider/theme/slide173.png
#  - image: slider/theme/slide174.png
#  - image: slider/theme/slide175.png
#  - image: slider/theme/slide176.png
#  - image: slider/theme/slide177.png
#  - image: slider/theme/slide178.png
#  - image: slider/theme/slide179.png
#  - image: slider/theme/slide180.png
#  - image: slider/theme/slide181.png
#  - image: slider/theme/slide182.png
#  - image: slider/theme/slide183.png
#  - image: slider/theme/slide184.png
#  - image: slider/theme/slide185.png
#  - image: slider/theme/slide186.png
#  - image: slider/theme/slide187.png
#  - image: slider/theme/slide188.png
#  - image: slider/theme/slide189.png
#  - image: slider/theme/slide190.png
#  - image: slider/theme/slide191.png
#  - image: slider/theme/slide192.png
#  - image: slider/theme/slide193.png
#  - image: slider/theme/slide194.png
#  - image: slider/theme/slide195.png
#  - image: slider/theme/slide196.png
#  - image: slider/theme/slide197.png
#  - image: slider/theme/slide198.png
#  - image: slider/theme/slide199.png
#  - image: slider/theme/slide200.png
#  - image: slider/theme/slide201.png
#  - image: slider/theme/slide202.png
#  - image: slider/theme/slide203.png
#  - image: slider/theme/slide204.png
#  - image: slider/theme/slide205.png
#  - image: slider/theme/slide206.png
#  - image: slider/theme/slide207.png
#  - image: slider/theme/slide208.png
#  - image: slider/theme/slide209.png
#  - image: slider/theme/slide210.png
#  - image: slider/theme/slide211.png
#  - image: slider/theme/slide212.png
#  - image: slider/theme/slide213.png
#  - image: slider/theme/slide214.png
#  - image: slider/theme/slide215.png
#  - image: slider/theme/slide216.png
#  - image: slider/theme/slide217.png
#  - image: slider/theme/slide218.png
#  - image: slider/theme/slide219.png
#  - image: slider/theme/slide220.png
#  - image: slider/theme/slide221.png
#  - image: slider/theme/slide222.png
#  - image: slider/theme/slide223.png
#  - image: slider/theme/slide224.png
#  - image: slider/theme/slide225.png
#  - image: slider/theme/slide226.png
#  - image: slider/theme/slide227.png
#  - image: slider/theme/slide228.png
#  - image: slider/theme/slide229.png
#  - image: slider/theme/slide230.png
#  - image: slider/theme/slide231.png
#  - image: slider/theme/slide232.png
#  - image: slider/theme/slide233.png
#  - image: slider/theme/slide234.png
#  - image: slider/theme/slide235.png
#  - image: slider/theme/slide236.png
#  - image: slider/theme/slide237.png
#  - image: slider/theme/slide238.png
#  - image: slider/theme/slide239.png
#  - image: slider/theme/slide240.png
#  - image: slider/theme/slide241.png
#  - image: slider/theme/slide242.png
#  - image: slider/theme/slide243.png
#  - image: slider/theme/slide244.png
#  - image: slider/theme/slide245.png
#  - image: slider/theme/slide246.png
#  - image: slider/theme/slide247.png
#  - image: slider/theme/slide248.png
#  - image: slider/theme/slide249.png
#  - image: slider/theme/slide250.png
#  - image: slider/theme/slide251.png
#  - image: slider/theme/slide252.png
#  - image: slider/theme/slide253.png
#  - image: slider/theme/slide254.png
#  - image: slider/theme/slide255.png
#  - image: slider/theme/slide256.png
#  - image: slider/theme/slide257.png
#  - image: slider/theme/slide258.png
#  - image: slider/theme/slide259.png
#  - image: slider/theme/slide260.png
#  - image: slider/theme/slide261.png
#  - image: slider/theme/slide262.png
#  - image: slider/theme/slide263.png
#  - image: slider/theme/slide264.png
#  - image: slider/theme/slide265.png
#  - image: slider/theme/slide266.png
#  - image: slider/theme/slide267.png
#  - image: slider/theme/slide268.png
#  - image: slider/theme/slide269.png
#  - image: slider/theme/slide270.png
#  - image: slider/theme/slide271.png
#  - image: slider/theme/slide272.png
#  - image: slider/theme/slide273.png
#  - image: slider/theme/slide274.png
#  - image: slider/theme/slide275.png
#  - image: slider/theme/slide276.png
#  - image: slider/theme/slide277.png
#  - image: slider/theme/slide278.png
#  - image: slider/theme/slide279.png
#  - image: slider/theme/slide280.png
#  - image: slider/theme/slide281.png
#  - image: slider/theme/slide282.png
#  - image: slider/theme/slide283.png
#  - image: slider/theme/slide284.png
#  - image: slider/theme/slide285.png
#  - image: slider/theme/slide286.png
#  - image: slider/theme/slide287.png
#  - image: slider/theme/slide288.png
#  - image: slider/theme/slide289.png
#  - image: slider/theme/slide290.png
#  - image: slider/theme/slide291.png
#  - image: slider/theme/slide292.png
#  - image: slider/theme/slide293.png
#  - image: slider/theme/slide294.png
#  - image: slider/theme/slide295.png
#  - image: slider/theme/slide296.png
#  - image: slider/theme/slide297.png
#  - image: slider/theme/slide298.png
#  - image: slider/theme/slide299.png
#  - image: slider/theme/slide300.png
