# Site settings
title: "#campuslauf16"
email: marie.timcke@journocode.com
url: http://www.tu-campuslauf.de
description: "Am 11. Mai fällt der Startschuss zum 32. Campuslauf der TU Dortmund.
Wieder werden sich Studierende und Externe in verschiedenen Disziplinen wie
dem Mathetower-Run oder dem Campuswalk messen.
In einem Countdown stimmt euch das Ressort <strong>Campus und Leben</strong> der
Pflichtlektüre Online
darauf ein und berichtet live vom Campussportevent des Jahres!"

# carousel
carousel:
  - image: /img/carousel/slide1.jpg
  - image: /img/carousel/slide2.jpg
  - image: /img/carousel/slide3.jpg
  - image: /img/carousel/slide4.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "#campuslauf16"


# Team names, titles and social links
people:
- name: Marie-Louise Timcke
  pic: 1
  position: Projektleitung & Webentwicklung
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
    - title: github
      url: https://github.com/marielouiese
    - title: globe
      url: http://datentaeter.de/

- name: Sakander Zirai
  pic: 2
  position: Webentwicklung
  social:
    - title: twitter
      url: http://www.twitter.com/suioni
    - title: github
      url: https://github.com/suioni
  #  - title: globe
  #    url: #






people2:
- name: Johannes Mohren
  pic: 7
  position: Ressortleitung
  social:
    - title: twitter
      url: https://twitter.com/Johannes_Mohren
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Julia Bernewasser
  pic: 8
  position: Ressortleitung
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Wenke
  pic: 3
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/Wenke_we
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Carola
  pic: 4
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #


- name: Hanna
  pic: 5
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Mara
  pic: 6
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Megan
  pic: 1
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Mara
  pic: 2
  position: Redaktion
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #






















# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: globe
    url: http://pflichtlektuere.com
  - title: twitter
    url: http://twitter.com/pflichtlektuere
  - title: facebook
    url: https://www.facebook.com/Pflichtlektuere-148575178511113/?fref=ts
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll




# Build settings
markdown: kramdown
permalink: pretty
